### ISSUE TITLE
Does the model use true main target value of y for calculating its prediction (self.y_T)?

### ISSUE THREAD

**Issue by heehwanpark** [yumoxu/stocknet-code#5]
I think there is a risk that model see the true main target value of y when it calculates y_T, which is a predicted value.

In the function \_create_vmd_with_zh_rec at Model.py, y_ values from self.y_ph (placeholder for y) are used for calculating h_z_post_t, z_post_t, and z_post_t_pdf in the tf.while loop. 
Since its condition "cond = lambda t, *args: t < self.max_n_days", model use every y_ values. These values are needed to get self.g_T and self.y_T (the prediction value of the main target y). 

``` 
y_ = tf.transpose(self.y_ph, [1, 0, 2])  # max_n_days * batch_size * y_size
        def _loop_body(t, ta_z_prior, ta_z_post, ta_kl):
            """
            iter body. iter over trading days.
            """
            with tf.variable_scope('iter_body', reuse=tf.AUTO_REUSE):
                ......
                with tf.variable_scope('h_z_post'):
                    h_z_post_t = self._linear([x[t], h_s[t], y_[t], z_post_t_1], self.z_size, 'tanh')
                with tf.variable_scope('z_post'):
                    z_post_t, z_post_t_pdf = self._z(h_z_post_t, is_prior=False)

                kl_t = ds.kl_divergence(z_post_t_pdf, z_prior_t_pdf)  # batch_size * z_size

                ta_z_prior = ta_z_prior.write(t, z_prior_t)  # write: batch_size * z_size
                ta_z_post = ta_z_post.write(t, z_post_t)  # write: batch_size * z_size
                ta_kl = ta_kl.write(t, kl_t)  # write: batch_size * 1

                return t + 1, ta_z_prior, ta_z_post, ta_kl
```

The problem is, it looks like that DataPipe._get_prices_and_ts( ) is the method to bring “y_batch” values to batch_dict (input batch), and the _get_prices_and_ts function put a y value of main target date into the "ys" list at the last position. 

```
with io.open(stock_movement_path, 'r', encoding='utf8') as movement_f:
        for line in movement_f:  # descend
            data = line.split('\t')
            t = datetime.strptime(data[0], '%Y-%m-%d').date()
            # logger.info(t)
            if t == main_target_date:
                # logger.info(t)
                ts.append(t)
                ys.append(_get_y(data))
                main_mv_percent = data[1]
                if -0.005 <= float(main_mv_percent) < 0.0055:  # discard sample with low movement percent
                    return None
```

It means the true value y of main target date can be used for predicting self.y_T, its prediction value, so model can cheat. I have tried to find any masking concept for this y value in Model.py, Executor.py, and DataPipe.py, but I could not find.

In fact, I have modified stocknet-code to apply Korean stock market. I refactored Executor.py and DataPipe.py to suit my purpose (I do not touch Model.py), and I am quite sure that my new codes follow your intention well (I checked my refactored code twice and compared batch results from my code to the results from yours). However, I found the model got 100% accuracy in the training phase, it means the model cheats. But it looks like stocknet codes run well with your own codes and data.

If you had handled this issue in advance, would you tell me how you handled it? It would be helpful for me.

Thank you for reading.

**Comment by heehwanpark** [comment]
I have misunderstood the paper and the codes.

**Comment by yjm1998** [comment]
i have the same question

**Comment by yjm1998** [comment]
i have also confused about this issue, so now i use _gen_func() to generate g_T for both training and testing, would you tell me how you handled it? It would be helpful for me.Thank you!

**Comment by kkew3** [comment]
See Equation (10) of the paper. You'll notice $y$ appears in both $q$ and the log likelihood. VAE trains by learning to probabilistically reconstruct the observation. Thus, the dependency on $y_T$ IMHO is not an issue.
